"""Export feature_stats and reports from vigilant.db into a seed_data.sql file."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / "apps" / "backend" / "core" / "database" / "vigilant.db"
SEED_SQL = ROOT / "apps" / "backend" / "core" / "database" / "seed_data.sql"
ARTIFACTS_DIR = ROOT / "apps" / "backend" / "artifacts" / "reports"


def _escape(value: object) -> str:
    """Return a SQL string literal for the given value (None → NULL)."""
    if value is None:
        return "NULL"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _build_feature_stats(conn) -> list[str]:
    rows = conn.execute(
        "SELECT feature_name, stats_json, updated_at FROM feature_stats ORDER BY feature_name"
    ).fetchall()
    lines = []
    for feature_name, stats_json, updated_at in rows:
        lines.append(
            f"INSERT OR REPLACE INTO feature_stats (feature_name, stats_json, updated_at)"
            f" VALUES ({_escape(feature_name)}, {_escape(stats_json)}, {_escape(updated_at)});"
        )
    return lines, len(rows)


def _build_reports(conn) -> list[str]:
    rows = conn.execute(
        "SELECT report_id, timestamp, report_type, model_version, metrics, artifacts"
        " FROM reports ORDER BY timestamp"
    ).fetchall()
    lines = []
    for report_id, timestamp, report_type, model_version, metrics, artifacts in rows:
        metrics_str = json.dumps(metrics) if metrics is not None else None
        artifacts_str = json.dumps(artifacts) if artifacts is not None else None
        lines.append(
            f"INSERT OR REPLACE INTO reports"
            f" (report_id, timestamp, report_type, model_version, metrics, artifacts)"
            f" VALUES ("
            f"{_escape(report_id)}, {_escape(timestamp)}, {_escape(report_type)},"
            f" {_escape(model_version)}, {_escape(metrics_str)}, {_escape(artifacts_str)}"
            f");"
        )
    return lines, len(rows)


def _build_reports_from_json(artifacts_dir: Path) -> tuple[list[str], int]:
    """Generate INSERT statements from .json report files when the DB table is empty."""
    lines = []
    for path in sorted(artifacts_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"  WARNING: skipping {path.name} — {exc}", file=sys.stderr)
            continue

        report_id = data.get("report_id") or path.stem
        timestamp = data.get("timestamp")
        report_type = data.get("report_type", "PRE_PROD")
        model_version = data.get("model_version")
        metrics = data.get("metrics")
        artifacts = data.get("artifacts")

        metrics_str = json.dumps(metrics) if metrics is not None else None
        artifacts_str = json.dumps(artifacts) if artifacts is not None else None

        lines.append(
            f"INSERT OR REPLACE INTO reports"
            f" (report_id, timestamp, report_type, model_version, metrics, artifacts)"
            f" VALUES ("
            f"{_escape(report_id)}, {_escape(timestamp)}, {_escape(report_type)},"
            f" {_escape(model_version)}, {_escape(metrics_str)}, {_escape(artifacts_str)}"
            f");"
        )
    return lines, len(lines)


def main() -> None:
    if not DB_PATH.exists():
        print(f"ERROR: database not found at {DB_PATH}", file=sys.stderr)
        sys.exit(1)

    try:
        import duckdb
    except ImportError:
        print("ERROR: duckdb not installed — run: pip install duckdb", file=sys.stderr)
        sys.exit(1)

    try:
        conn = duckdb.connect(str(DB_PATH), read_only=True)
    except Exception as exc:
        print(f"ERROR: could not open database: {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        feature_lines, n_features = _build_feature_stats(conn)
        report_lines, n_reports = _build_reports(conn)
    except Exception as exc:
        print(f"ERROR: failed to read tables: {exc}", file=sys.stderr)
        conn.close()
        sys.exit(1)
    finally:
        conn.close()

    if n_reports == 0:
        if ARTIFACTS_DIR.exists():
            rel = ARTIFACTS_DIR.relative_to(ROOT)
            print(f"  reports table is empty — falling back to {rel}/")
            report_lines, n_reports = _build_reports_from_json(ARTIFACTS_DIR)
        else:
            print("  reports table is empty and no artifacts/reports/ directory found — skipping.")

    blocks: list[str] = [
        "-- Auto-generated by scripts/migration.py — do not edit manually",
        "",
        "BEGIN;",
        "",
    ]

    if feature_lines:
        blocks.append("-- feature_stats")
        blocks.extend(feature_lines)
        blocks.append("")

    if report_lines:
        blocks.append("-- reports")
        blocks.extend(report_lines)
        blocks.append("")

    blocks.append("COMMIT;")
    blocks.append("")

    SEED_SQL.write_text("\n".join(blocks), encoding="utf-8")

    rel = SEED_SQL.relative_to(ROOT)
    print(f"  ✓ Exported {n_features} feature_stats rows")
    print(f"  ✓ Exported {n_reports} reports rows")
    print(f"  ✓ Written → {rel}")


if __name__ == "__main__":
    main()
